AlignityApp/ViewModels/OpportunityViewModel.cs
using AlignityApp.Models;
using System.Collections.Generic;

namespace AlignityApp.ViewModels
{
    public class OpportunityViewModel
    {
        public User User { get; set; }
        public List<User> Salaries { get; set; }
        public Customer Customer { get; set; }
        public List<JobInterview> JobInterviews { get; set; }
        public Dictionary<string, List<User>> SalariesCustomer { get; set; }
    }
}

AlignityApp/Controllers/OpportunityController.cs
using AlignityApp.Models;
using AlignityApp.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Xml.Linq;
using System;
using System.Linq;

namespace AlignityApp.Controllers
{
    public class OpportunityController : Controller
    {
        public IActionResult Index(int id)
        {
            using (Dal dal = new Dal())
            {
                List<JobInterview> jobInterviews = dal.GetAllJobInterviews();
                Dictionary<string, List<User>> keyValuePairs = new Dictionary<string, List<User>>();
                
                foreach (var jobInterview in jobInterviews)
                {
                    List<User> salaries = dal.GetSalariedByCustomer(jobInterview.CustomerId);
                    string brand = dal.GetCustomerById(jobInterview.CustomerId).Brand;

                    if (!keyValuePairs.Any(kvp => kvp.Key == brand && kvp.Value.SequenceEqual(salaries)))
                    {
                        keyValuePairs.Add(brand, salaries);
                    }
                }

                OpportunityViewModel ovm = new OpportunityViewModel()
                {
                    User = dal.GetUser(id),
                    JobInterviews = jobInterviews,
                    SalariesCustomer = keyValuePairs              
                };

                return View(ovm);
            }
        }

        public IActionResult CreateOpportunity(int id)
        {
            using (Dal dal = new Dal())
            {
                if (id != 0)
                {
                    List<Customer> customers = dal.GetAllCustomers();
                    ViewBag.listCustomers = customers;

                    List<User> salaries = dal.GetAllSalaries(id);
                    ViewBag.listSalaries = salaries;

                    Customer customer = dal.GetCustomerById(dal.GetJIById(dal.GetJobInterview().Id).CustomerId);

                    List<SJobInterview> salariedForJob = dal.GetSalariesByJId(dal.GetJobInterview().Id);

                    if (customer != null)
                    {
                        OpportunityViewModel ovm = new OpportunityViewModel()
                        {
                            User = dal.GetUser(id),
                            Salaries = dal.GetSalariesById(salariedForJob),
                            Customer = customer,
                        };
                        return View(ovm);
                    }
                    else
                    {
                        OpportunityViewModel ovm2 = new OpportunityViewModel()
                        {
                            User = dal.GetUser(id),
                            Salaries = dal.GetSalariesById(salariedForJob),
                            Customer = new Customer(),
                        };
                        return View(ovm2);
                    }
                }
                else
                {
                    return View("Error");
                }
            }
        }

        [HttpPost]
        public IActionResult CreateOpportunity2(int id, int CustomerId)
        {
            using (Dal dal = new Dal())
            {
                if (id != 0)
                {
                    dal.CreateJobInterview("Mon contrat", CustomerId);
                    return RedirectToAction("CreateOpportunity", new { @id = id });
                }
                else
                {
                    return View("Error");
                }
            }
        }

        [HttpPost]
        public IActionResult CreateOpportunity3(int id, int SalariedId)
        {
            using (Dal dal = new Dal())
            {
                if (id != 0)
                {
                    dal.ModifySJobInterview(SalariedId);
                    return RedirectToAction("CreateOpportunity", new { @id = id });
                }
                else
                {
                    return View("Error");
                }
            }
        }

        [HttpPost]
        public IActionResult ValidateOpportunity(int id)
        {
            using (Dal dal = new Dal())
            {
                if (id != 0)
                {
                    dal.UpdateJobInterview(dal.GetJIById(dal.GetJobInterview().Id));
                    return RedirectToAction("CreateOpportunity", new { @id = id });
                }
                else
                {
                    return View("Error");
                }
            }
        }

        public IActionResult DeleteOpportunity(int id)
        {
            using (Dal dal = new Dal())
            {
                if (id != 0)
                {
                    dal.DeleteSJobInterview();
                    dal.DeleteJobInterview();
                    return RedirectToAction("CreateOpportunity", new { @id = id });
                }
                else
                {
                    return View("Error");
                }
            }
        }

        public IActionResult OpportunityAccepted(int id)
        {
            using (Dal dal = new Dal())
            {
                if (id != 0)
                {
                    return View();
                }
                else
                {
                    return View("Error");
                }
            }
        }

        public IActionResult OpportunityRefused(int id)
        {
            using (Dal dal = new Dal())
            {
                if (id != 0)
                {
                    return View();
                }
                else
                {
                    return View("Error");
                }
            }
        }
    }
}

AlignityApp/Views/Opportunity/Contract.cshtml
@model AlignityApp.ViewModels.OpportunityViewModel
@{
    Layout = "_LayoutApp";
    ViewBag.Title = "Tous mes contrats";
}

<h1>Contract</h1>

AlignityApp/Views/Opportunity/CreateOpportunity.cshtml
@model AlignityApp.ViewModels.OpportunityViewModel
@{
    Layout = "_LayoutApp";
    ViewBag.Title = "Créer une nouvelle opportunité";
}
    <h3 class="text-primary text-center mb-5">Vous pouvez choisir les participants au futur entretien d'embauche</h3>

<div class="row">


    <div class="col-lg-6">

        <!-- Basic Card Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-dark">Paticipants</h6>
            </div>
            <div class="card-body">
 
                @using (Html.BeginForm("CreateOpportunity2", "Opportunity", FormMethod.Post, new { @class = "row justify-content-around mb-4" }))
                {
                    <input type="hidden" name="id" value="@User.FindFirst("Sid").Value" />
                    @Html.Label("Choisir un Client :")
                    @Html.DropDownList("CustomerId", new SelectList(ViewBag.listCustomers, "Id", "Brand"), new {@class ="col-6 p-2"})
                    <input class="btn btn-warning col-2" type="submit" value="Envoyer" />
                }

                @using (Html.BeginForm("CreateOpportunity3", "Opportunity", FormMethod.Post, new { @class = "row justify-content-around" }))
                {
                    <input type="hidden" name="id" value="@User.FindFirst("Sid").Value" />
                    @Html.Label("Choisir un salarié :")
                    @Html.DropDownList("SalariedId", new SelectList(ViewBag.listSalaries, "Id", "Name"), new {@class="col-6 p-2"})

                    <input class="btn btn-warning col-2" type="submit" value="Envoyer" />
                }

            </div>
        </div>

    </div>

    <div class="col-lg-6">

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-dark">Valider l'entretien</h6>
            </div>

            <div class="card-body">

                @using (Html.BeginForm("ValidateOpportunity", "Opportunity", FormMethod.Post))
                {
                    <h5 class="card-title"> <span>Client : </span>@Model.Customer.Brand</h5>

                @if (Model.Salaries != null)
                {
                    @for (int i = 1; i < Model.Salaries.Count + 1; i++)
                    {
                        <input type="hidden" name="id" value="@User.FindFirst("Sid").Value" />
                        <div class="card-body border-bottom border-success bg-light">
                            <p>Candidat n° @i </p>
                            @Html.TextBoxFor(m => m.Salaries[i - 1].Id, new {@class="d-none"})
                            @Html.TextBoxFor(m => m.Salaries[i - 1].Name, new {@class="border-0", disabled="disabled"})
                            @Html.TextBoxFor(m => m.Salaries[i - 1].Firstname, new {@class="border-0", disabled="disabled"})
                            <div>
                                <span>TJM : </span>
                                @Html.TextBoxFor(m => m.Salaries[i - 1].RateTjm, new {@class="border-0", disabled="disabled"})
                            </div>
                        </div>
                    }
                }

                <div class="col-12 mt-5 d-flex justify-content-around">
                    <button class="btn btn-warning m-2" type="submit">Valider</button>
                    <a class="btn btn-secondary m-2" href="~/Opportunity/DeleteOpportunity/?id=@(int.Parse(User.FindFirst("Sid").Value))">
                        Annuler
                    </a>
                </div>
                }
     
            </div>
        </div>

    </div>
</div>

AlignityApp/Views/Opportunity/Index.cshtml
@model AlignityApp.ViewModels.OpportunityViewModel
@{
    Layout = "_LayoutApp";
    ViewBag.Title = "Opportunités d'embauche";
}

<h3 class="text-center text-primary mb-5">Mes opprotunités de contrat</h3>

<div class="row">
    @foreach (var salariesCustomer in Model.SalariesCustomer)
    {
        <div class="col-lg-4">

            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Entretien en cours</h6>
                </div>

                <div class="card-body">

                    <h5 class="card-title p-2 border-bottom-primary"> <span>Client : </span>@salariesCustomer.Key</h5>

                    @foreach (var salaried in salariesCustomer.Value)
                    {
                        <div class="px-2 pt-3 border-bottom border-primary">
                            <span>Candidat : @salaried.Name @salaried.Firstname</span>
                            <p>TJM : @salaried.RateTjm</p>
                        </div>
                    }

                </div>

                @*<div class="mb-4 d-flex justify-content-around">
                    <a id= 1 + "@salariesCustomer.Key" class= "btn btn-primary" href="~/Opportunity/OpportunityAccepted/?id=@(int.Parse(User.FindFirst("Sid").Value))">
                        Accepté
                    </a>

                    <a id= 2 + "@salariesCustomer.Key" class="btn btn-secondary" href="~/Opportunity/OpportunityRefused/?id=@(int.Parse(User.FindFirst("Sid").Value))">
                        Refusé
                    </a>
                </div>*@

            </div>
        </div>
    }
</div>