AlignityApp/ViewModels/TeamsViewModel.cs
using AlignityApp.Models;
using System.Collections.Generic;

namespace AlignityApp.ViewModels
{
    public class TeamsViewModel
    {
        public User User { get; set; }
        public List<User> Users { get; set; }
        public List<User> Salaries { get; set; }
        public List<Cra> Cras { get; set; }
        public int getScreen { get; set; }
        public User Salaried { get; set; }
        public int CASalaried { get; set; }
    }
}

AlignityApp/Controllers/TeamController.cs
using AlignityApp.Models;
using AlignityApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AlignityApp.Controllers
{
    [Authorize]
    public class TeamController : Controller
    {
        public IActionResult Index(int id)
        {
            TeamsViewModel tvm = new TeamsViewModel();
            using (Dal dal = new Dal())
            {
                if (id == -1)
                {
                    tvm.getScreen = 1;
                    tvm.Salaries = dal.GetSalariedWithoutManager();
                    tvm.User = dal.GetUser(id);

                    return View(tvm);
                }
                else
                {
                    if (User.IsInRole("ADMINISTRATOR") && id == 0)
                    {
                        tvm.Users = dal.GetAllManager();

                        return View(tvm);
                    }
                    else
                    {
                        tvm.User = dal.GetUser(id);
                        tvm.Users = dal.GetUsersByManagerId(id);
                        tvm.Cras = dal.GetTeamCras(id);

                        if (id == 0)
                        {
                            tvm.Salaries = dal.GetAllUsers();
                            tvm.Cras = dal.GetAllCras();
                            return View(tvm);
                        }
                        else
                        {
                            tvm.User = dal.GetUser(id);
                            tvm.Salaries = dal.GetUsersByManagerId(id);
                            tvm.Cras = dal.GetTeamCras(id);
                            return View(tvm);
                        }
                    }
                }
            }
        }

        [HttpPost]
        public IActionResult ModalIndex(int id, TeamsViewModel tvm)
        {
            using (Dal dal = new Dal())
            {
                if (id != 0)
                {
                    dal.UpdateTJM(tvm.Salaried.Id, tvm.Salaried.RateTjm);
                    return RedirectToAction("Index", new { @id = id });
                }
                else
                {
                    return View("Error");
                }
            }
        }
    }
}

AlignityApp/Views/Team/Index.cshtml
@model AlignityApp.ViewModels.TeamsViewModel
@{
    Layout = "_LayoutApp";
    ViewBag.Title = "Mon équipe";
}

@using Microsoft.AspNetCore.Routing;


@if (User.IsInRole("MANAGER") || (Model.User != null) || Model.getScreen == 1)
{

    <!-- DataTales Example -->
    <!-- DataTales -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            @if (Model.User != null)
            {
                <h6 class="m-0 font-weight-bold text-primary">Manager @Model.User.Name</h6>
            }
            else
            {
                <h6 class="m-0 font-weight-bold text-primary">Voici les @Model.Salaries.Count salariés sans manager</h6>
            }
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr class="table-dark">
                            <th class="bg-dark" scope="col">Nom</th>
                            <th class="bg-dark" scope="col">Prénom</th>
                            <th class="bg-dark" scope="col">Téléphone</th>
                            <th class="bg-dark" scope="col">Code postal</th>
                            <th class="bg-dark" scope="col">Email</th>
                            <th class="bg-dark" scope="col">Date entrée</th>
                            <th class="bg-dark" scope="col">Métier</th>
                            <th class="bg-dark" scope="col">TJM</th>
                            <th class="bg-dark" scope="col">CA</th>
                            <th class="bg-dark" scope="col">Détails salarié</th>
                            <th class="bg-dark" scope="col">CRAs </th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr class="table-dark">
                            <th class="bg-dark" scope="col">Nom</th>
                            <th class="bg-dark" scope="col">Prénom</th>
                            <th class="bg-dark" scope="col">Téléphone</th>
                            <th class="bg-dark" scope="col">Code postal</th>
                            <th class="bg-dark" scope="col">Email</th>
                            <th class="bg-dark" scope="col">Date entrée</th>
                            <th class="bg-dark" scope="col">Métier</th>
                            <th class="bg-dark" scope="col">TJM</th>
                            <th class="bg-dark" scope="col">CA</th>
                            <th class="bg-dark" scope="col">Détails salarié</th>
                            <th class="bg-dark" scope="col">CRAs </th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (AlignityApp.Models.User salaried in Model.Salaries)
                        {
                            <tr>
                                
                                <td>@salaried.Name</td>
                                <td>@salaried.Firstname</td>
                                <td>@salaried.PhoneNumber</td>
                                <td>@salaried.PostalCode</td>
                                <td>@salaried.Email</td>
                                <td>@salaried.CreationDate.ToString("dd/MM/yyyy")</td>
                                @if (@salaried.UserJob.ToString() == "TECHNICIAN")
                                {
                                    <td>Tech</td>
                                }
                                @if (@salaried.UserJob.ToString() == "HR_MANAGER")
                                {
                                    <td>RH</td>
                                }
                                @if (@salaried.UserJob.ToString() == "COMMERCIAL")
                                {
                                    <td>Commercial</td>
                                }
                                @if (@salaried.UserJob.ToString() == "SECRETARY")
                                {
                                    <td>Secrétaire</td>
                                }
                                @if (@salaried.UserJob.ToString() == "DIRECTOR")
                                {
                                    <td>Directeur</td>
                                }
                                <td>

                                    <table class="mt-1">
                                        <tr>
                                            <td>@salaried.RateTjm</td>
                                            @if (User.IsInRole("MANAGER"))
                                            {
                                                
                                            <td>
                                                <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modal-@salaried.Id">
                                                    <i class="far fa-edit"></i>
                                                </button>

                                                <div class="modal fade" id="modal-@salaried.Id" tabindex="-1" role="dialog" aria-labelledby="modal-@salaried.Id-label" aria-hidden="true">
                                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h5 class="modal-title" id="modal-@salaried.Id-label">TJM @salaried.Name @salaried.Firstname</h5>
                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                @using (Html.BeginForm("ModalIndex", "Team", FormMethod.Post))
                                                                {
                                                                    <input type="hidden" name="id" value="@User.FindFirst("Sid").Value" />
                                                                    <fieldset class="d-flex justify-content-between">
                                                                        <legend>Entrer le nouveau TJM</legend>
                                                                        @Html.TextBoxFor(m => salaried.Id, new {@class = "d-none"})
                                                                        @Html.TextBoxFor(m => salaried.RateTjm)
                                                                        @Html.ValidationMessageFor(m => salaried.RateTjm)
                                                                        <input class="btn btn-warning" type="submit" value="Modifier" />
                                                                    </fieldset>
                                                                }
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                            }
                                        </tr>
                                    </table>

                                </td>

                                <td>@salaried.CA</td>
                                
                                <td>
                                    <a class="btn btn-primary m-3" href="/user?id=@salaried.Id">
                                        <i class="far fa-eye"></i>
                                    </a>
                                </td>
                                <td>
                                    <a class="btn btn-success m-3" href="/listCra/?id=@salaried.Id">
                                        <i class="far fa-eye"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

@if (User.IsInRole("ADMINISTRATOR") && Model.User == null && Model.getScreen == 0)
{
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Les @Model.Users.Count Managers de l'Alignity</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr class="table-dark">
                            <th class="bg-dark">Nom</th>
                            <th class="bg-dark">Prénom</th>
                            <th class="bg-dark">Téléphone</th>
                            <th class="bg-dark">Email</th>
                            <th class="bg-dark">Métier</th>
                            <th class="bg-dark">Editer</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr class="table-dark">
                            <th class="bg-dark">Nom</th>
                            <th class="bg-dark">Prénom</th>
                            <th class="bg-dark">Téléphone</th>
                            <th class="bg-dark">Email</th>
                            <th class="bg-dark">Métier</th>
                            <th class="bg-dark">Editer </th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (AlignityApp.Models.User user in Model.Users)
                        {
                            <tr>
                                <td>@user.Name</td>
                                <td>@user.Firstname</td>
                                <td>@user.PhoneNumber</td>
                                <td>@user.Email</td>

                                @if (@user.UserJob.ToString() == "TECHNICIAN")
                                {
                                    <td>Tech</td>
                                }

                                @if (@user.UserJob.ToString() == "HR_MANAGER")
                                {
                                    <td>RH</td>
                                }

                                @if (@user.UserJob.ToString() == "COMMERCIAL")
                                {
                                    <td>Commercial</td>

                                }

                                @if (@user.UserJob.ToString() == "SECRETARY")
                                {
                                    <td>Secrétaire</td>

                                }

                                @if (@user.UserJob.ToString() == "DIRECTOR")
                                {
                                    <td>Directeur</td>
                                }

                                <td><a href="/Team/?id=@user.Id" class="btn btn-primary btn-sm" style="margin-right:20px">voir son équipe</a><a href="/User/?id=@user.Id" class="btn btn-info btn-sm">voir manager</a></td>

                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

}

@section Css {
    <link href="/css/listCra/dataTables.bootstrap4.min.css" rel="stylesheet">
}

@section Scripts {
    <!-- Page level plugins -->
    <script src="/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="/vendor/datatables/dataTables.bootstrap4.min.js"></script>
    <!-- Page level custom scripts -->
    <script src="/js/demo/datatables-demo.js"></script>
}